### ISSUE TITLE
board out of date 

### ISSUE THREAD

**Issue by VictorDuma-zz** [dhylands/BRAINPAD#1]
It looks like there are many changes in the micropython, it always evolving, and I really glad to see that. Thank you! Now I try to run BrainPad and in order to do that I changed mpconfigboard.mk the same like NUCLEO_F401RE board. But after compiling and flashing only blinking LEDs green and blue (in the main.c no one errors with blue led). Should I make some other changes?

**Comment by dhylands** [comment]
This should now be resolved.
```
MicroPython v1.9.4-138-g039f196c5 on 2018-06-07; BRAINPAD with STM32F401RE
Type "help()" for more information.
>>> 
```

**Comment by dhylands** [comment]
Fixed in https://github.com/dhylands/BRAINPAD/commit/25e5293d8d964a15845717c58e07b99fc12f829d

**Comment by VictorDuma-zz** [comment]
Thank you very much! I appreciate it. Have a nice weekend!
