### ISSUE TITLE
Servo pin assignment possibly incorrect

### ISSUE THREAD

**Issue by scruss** [dhylands/BRAINPAD#2]
pins.csv has [servo](https://github.com/dhylands/BRAINPAD/blob/master/pins.csv#L21) definitions as follows:

    SERVO1 | PA3
    SERVO2 | PA0

but schematic shows Servo1 on PA8 and Servo2 (possibly; it says DC Motor on that connector) on PA0.

Is it just a case of modifying the CSV and make will do its thing?

**Comment by davehylands** [comment]
Yep.

**Comment by scruss** [comment]
Thanks! Servo1 is working a treat!
